### ISSUE TITLE
After upgrading from 1.1.2 to 1.1.3

### ISSUE THREAD

**Issue by ccamacho** [haidaraM/ansible-playbook-grapher#119]
**Describe the bug**
After upgrading the library it started to fail with:

```
Done parsing Play: Run cluster deployment on prepared hypervisors (1) **********
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook-grapher", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/cli.py", line 249, in main
    cli.run()
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/cli.py", line 71, in run
    svg_path = renderer.render(
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/renderer.py", line 114, in render
    self._convert_to_graphviz()
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/renderer.py", line 391, in _convert_to_graphviz
    self.render_node(
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/renderer.py", line 153, in render_node
    self.render_block(
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/renderer.py", line 244, in render_block
    self.render_node(
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/renderer.py", line 161, in render_node
    self.render_role(
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/renderer.py", line 295, in render_role
    role_color = ":".join([c[0] for c in colors])
  File "/usr/local/lib/python3.8/dist-packages/ansibleplaybookgrapher/renderer.py", line 295, in <listcomp>
    role_color = ":".join([c[0] for c in colors])
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.
```

**Versions:**
Outputs of :
 - `ansible --version`
 ansible-5.1.0 ansible-compat-2.2.0 ansible-core-2.12.8
 - `ansible-playbook-grapher --version`
 Error from 1.1.2(works) to 1.1.3(broken)

**Comment by ccamacho** [comment]
This is how the Playbooks diagrams look like: https://docs.kubeinit.org/playbook_diagrams.html#playbook-diagrams

**Comment by haidaraM** [comment]
Can you try with the version on the linked [PR](https://github.com/haidaraM/ansible-playbook-grapher/pull/120) (branch `fix/IterationOnNonType`)? It should be fixed now.

I introduced a change in 1.1.3 to render a single node when multiple plays use the same role, but I think I will add this behavior under flag instead. Not sure if we always want to do that. Let me know what you think.

**Comment by haidaraM** [comment]
Let me know if you still face the issue. The fix will be available in the next release (soon)

**Comment by ccamacho** [comment]
Hi!
Indeed it is fixed now, tested in https://github.com/Kubeinit/kubeinit/pull/691

Do you know when you will be releasing a new tag?

Thanks!

**Comment by haidaraM** [comment]
Most likely this week
