### ISSUE TITLE
IndexError - out of range

### ISSUE THREAD

**Issue by denics** [haidaraM/ansible-playbook-grapher#20]
**Describe the bug**
It seems that graphviz has some problems with the generated tree. This is the error message:

```python
Traceback (most recent call last):
  File "/home/me/.local/bin/ansible-playbook-grapher", line 10, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python2.7/site-packages/ansibleplaybookgrapher/cli.py", line 168, in main
    cli.run()
  File "/home/me/.local/lib/python2.7/site-packages/ansibleplaybookgrapher/cli.py", line 159, in run
    return grapher.post_process_svg()
  File "/home/me/.local/lib/python2.7/site-packages/ansibleplaybookgrapher/grapher.py", line 258, in post_process_svg
    post_processor.post_process(graph_representation=self.graph_representation)
  File "/home/me/.local/lib/python2.7/site-packages/ansibleplaybookgrapher/utils.py", line 196, in post_process
    self._insert_graph_representation(graph_representation)
  File "/home/me/.local/lib/python2.7/site-packages/ansibleplaybookgrapher/utils.py", line 207, in _insert_graph_representation
    element = self.root.xpath("ns:g/*[@id='%s']" % node, namespaces={'ns': SVG_NAMESPACE})[0]
IndexError: list index out of range
```

**To Reproduce**
Launching the command to generate a graph`~/.local/bin/ansible-playbook-grapher  --include-role-tasks -v site.yml`

**Expected behavior**
Get a svg that includes roles' tasks. The command works fine if it is launched *without* `include-role-tasks`

**Screenshots**

**Versions:**
ansible-playbook-grapher 0.9.1 (with ansible 2.8.2)

**Comment by haidaraM** [comment]
Interesting. Can show me the `site.yml` or a subset of it that fails ?
