### ISSUE TITLE
Argument parsing fails with ansible 2.9.4

### ISSUE THREAD

**Issue by sylock** [haidaraM/ansible-playbook-grapher#27]
**Describe the bug**
When trying to ask for help it fails while parsing arguments.

ansible-playbook-grapher --help
Traceback (most recent call last):
  File "/home/smals-nim/venvs/ansible/bin/ansible-playbook-grapher", line 8, in <module>
    sys.exit(main())
  File "/home/smals-nim/venvs/ansible/lib/python3.6/site-packages/ansibleplaybookgrapher/cli.py", line 166, in main
    cli.parse()
  File "/home/smals-nim/venvs/ansible/lib/python3.6/site-packages/ansible/cli/__init__.py", line 362, in parse
    self.init_parser()
  File "/home/smals-nim/venvs/ansible/lib/python3.6/site-packages/ansibleplaybookgrapher/cli.py", line 118, in init_parser
    _add_my_options(self.parser)
  File "/home/smals-nim/venvs/ansible/lib/python3.6/site-packages/ansibleplaybookgrapher/cli.py", line 35, in _add_my_options
    parser.add_option('-i', '--inventory', dest='inventory', action="append",
AttributeError: 'ArgumentParser' object has no attribute 'add_option'

**Versions:**
Outputs of :
 - `ansible --version`: ansible --version
 - `ansible-playbook-grapher --version`: doesn't work but pip give me: 0.9.1

**Additional context**
- python 3.6 with virtual env

**Comment by stanislaw55** [comment]
This bug forces me to drop usage of this tool

**Comment by cloudwheels** [comment]
Same problem. Python 3.7.3
ansible --version
ansible 2.9.5

**Comment by cloudwheels** [comment]
Is this the same as #23 ?
Does the tool need a new release (v. 0.9.1 installed with pip install) ?

**Comment by cloudwheels** [comment]
I removed 2.9.5 and installed 2.8.5 and all working ok.

**Comment by haidaraM** [comment]
This is already fixed in #25 . Will drop a new release soon

**Comment by haidaraM** [comment]
Check the last version 0.9.2
